import { IProduct } from './product.model';

export const PRODUCTS: IProduct[] = [
  // Head Category
  {
    id: 1,
    name: 'Advanced Robot Head',
    description: 'High-tech robotic head with sensors',
    price: 1200.0,
    imageName: 'assets/images/robot-head.jpeg',
    category: 'Head',
    discount: 0.1,
  },
  {
    id: 2,
    name: 'Friendly Robot Head',
    description: 'Friendly robot head with expressive features',
    price: 945.0,
    imageName: 'assets/images/robot-head1.jpeg',
    category: 'Head',
    discount: 0.0,
  },
  {
    id: 3,
    name: 'Stealth Robot Head',
    description: 'Low-profile robot head with night vision',
    price: 1300.0,
    imageName: 'assets/images/robot-head2.jpeg',
    category: 'Head',
    discount: 0.05,
  },
  {
    id: 4,
    name: 'AI-Powered Robot Head',
    description: 'Robot head with built-in AI assistant',
    price: 1500.0,
    imageName: 'assets/images/robot-head3.jpeg',
    category: 'Head',
    discount: 0.08,
  },

  // Legs Category
  {
    id: 5,
    name: 'Strong Robot Legs',
    description: 'Powerful legs with high mobility',
    price: 1050.0,
    imageName: 'assets/images/robot-leg.jpeg',
    category: 'Legs',
    discount: 0,
  },
  {
    id: 6,
    name: 'Friendly Robot Legs',
    description: 'Lightweight robot legs for casual movement',
    price: 980.0,
    imageName: 'assets/images/robot-leg1.jpeg',
    category: 'Legs',
    discount: 0,
  },
  {
    id: 7,
    name: 'Heavy-Duty Robot Legs',
    description: 'Durable legs for industrial use',
    price: 1250.0,
    imageName: 'assets/images/robot-leg2.jpeg',
    category: 'Legs',
    discount: 0,
  },
  {
    id: 8,
    name: 'Speedy Robot Legs',
    description: 'Optimized for high-speed movement',
    price: 1400.0,
    imageName: 'assets/images/robot-leg3.jpeg',
    category: 'Legs',
    discount: 0.1,
  },

  // Arms Category
  {
    id: 9,
    name: 'Advanced Robot Arms',
    description: 'High-tech robotic arms with precision control',
    price: 1100.0,
    imageName: 'assets/images/robot-arm.jpeg',
    category: 'Arms',
    discount: 0,
  },
  {
    id: 10,
    name: 'Friendly Robot Arm',
    description: 'Friendly robot arm with customizable grip',
    price: 1023.0,
    imageName: 'assets/images/robot-arm1.jpeg',
    category: 'Arms',
    discount: 0,
  },
  {
    id: 11,
    name: 'Heavy Lifting Robot Arms',
    description: 'Capable of lifting heavy loads with ease',
    price: 1350.0,
    imageName: 'assets/images/robot-arm2.jpeg',
    category: 'Arms',
    discount: 0.14,
  },
  {
    id: 12,
    name: 'Multi-Purpose Robot Arms',
    description: 'Versatile arms with multiple tool attachments',
    price: 1500.0,
    imageName: 'assets/images/robot-arm3.jpeg',
    category: 'Arms',
    discount: 0,
  },

  // Torso Category (New)
  {
    id: 13,
    name: 'Reinforced Robot Torso',
    description: 'Durable and impact-resistant torso structure',
    price: 1700.0,
    imageName: 'assets/images/robot-torso.jpeg',
    category: 'Torso',
    discount: 0,
  },
  {
    id: 14,
    name: 'Lightweight Robot Torso',
    description: 'Light and flexible torso for agile movement',
    price: 1600.0,
    imageName: 'assets/images/robot-torso1.jpeg',
    category: 'Torso',
    discount: 0,
  },
  {
    id: 15,
    name: 'Energy-Efficient Robot Torso',
    description: 'Optimized for long battery life',
    price: 1750.0,
    imageName: 'assets/images/robot-torso2.jpeg',
    category: 'Torso',
    discount: 0.15,
  },
  {
    id: 16,
    name: 'Combat-Ready Robot Torso',
    description: 'Armor-plated torso for high-endurance missions',
    price: 1900.0,
    imageName: 'assets/images/robot-torso3.jpeg',
    category: 'Torso',
    discount: 0,
  },
];
